parameters:
  rustup_toolchain: 'stable'
  working_directory: './'
jobs:
- job: rustfmt
  pool:
    vmImage: ubuntu-16.04
  steps:
    - template: /az-pipeline/unstable/rustup.yml
      parameters:
        rustup_toolchain: ${{ parameters.rustup_toolchain }}
        components:
          - rustfmt
    - script: |
        cargo fmt -- --check
      workingDirectory: ${{ parameters.working_directory }}
      displayName: Run rustfmt
