parameters:
  rustup_toolchain: 'stable'
  working_directory: './'
jobs:
- job: warnings
  pool:
    vmImage: ubuntu-16.04
  steps:
    - template: /az-pipeline/unstable/rustup.yml
      parameters:
        rustup_toolchain: ${{ parameters.rustup_toolchain }}
    - script: |
        cargo check --tests
      workingDirectory: ${{ parameters.working_directory }}
      env:
        RUSTFLAGS: "-D warnings"
      displayName: Run check
